[package]
name = "arcane_fps"
version = "0.1.0"
edition = "2021"

[dependencies]
arcane_core = {path="../arcane_core"}
arcane_keybindings = {path="../arcane_keybindings"}

ratatui = {version="0.29"}
error_mancer = "0.4"

serde = {version="1.0", features=["derive"]}
typetag = "0.2"
